//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB5_1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="A", Namespace="http://schemas.datacontract.org/2004/07/LB5_1")]
    public partial class A : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private float fField;
        
        private int kField;
        
        private string sField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float f
        {
            get
            {
                return this.fField;
            }
            set
            {
                this.fField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int k
        {
            get
            {
                return this.kField;
            }
            set
            {
                this.kField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string s
        {
            get
            {
                return this.sField;
            }
            set
            {
                this.sField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IWCFSiplex")]
public interface IWCFSiplex
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSiplex/Add", ReplyAction="http://tempuri.org/IWCFSiplex/AddResponse")]
    int Add(int x, int y);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSiplex/Add", ReplyAction="http://tempuri.org/IWCFSiplex/AddResponse")]
    System.Threading.Tasks.Task<int> AddAsync(int x, int y);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSiplex/Concat", ReplyAction="http://tempuri.org/IWCFSiplex/ConcatResponse")]
    string Concat(string str, double d);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSiplex/Concat", ReplyAction="http://tempuri.org/IWCFSiplex/ConcatResponse")]
    System.Threading.Tasks.Task<string> ConcatAsync(string str, double d);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSiplex/Sum", ReplyAction="http://tempuri.org/IWCFSiplex/SumResponse")]
    LB5_1.A Sum(LB5_1.A objOne, LB5_1.A objTwo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSiplex/Sum", ReplyAction="http://tempuri.org/IWCFSiplex/SumResponse")]
    System.Threading.Tasks.Task<LB5_1.A> SumAsync(LB5_1.A objOne, LB5_1.A objTwo);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IWCFSiplexChannel : IWCFSiplex, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class WCFSiplexClient : System.ServiceModel.ClientBase<IWCFSiplex>, IWCFSiplex
{
    
    public WCFSiplexClient()
    {
    }
    
    public WCFSiplexClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public WCFSiplexClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WCFSiplexClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WCFSiplexClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int Add(int x, int y)
    {
        return base.Channel.Add(x, y);
    }
    
    public System.Threading.Tasks.Task<int> AddAsync(int x, int y)
    {
        return base.Channel.AddAsync(x, y);
    }
    
    public string Concat(string str, double d)
    {
        return base.Channel.Concat(str, d);
    }
    
    public System.Threading.Tasks.Task<string> ConcatAsync(string str, double d)
    {
        return base.Channel.ConcatAsync(str, d);
    }
    
    public LB5_1.A Sum(LB5_1.A objOne, LB5_1.A objTwo)
    {
        return base.Channel.Sum(objOne, objTwo);
    }
    
    public System.Threading.Tasks.Task<LB5_1.A> SumAsync(LB5_1.A objOne, LB5_1.A objTwo)
    {
        return base.Channel.SumAsync(objOne, objTwo);
    }
}
